### ISSUE TITLE
just a note

### ISSUE THREAD

**Issue by alexdrk** [ValdikSS/skype-poll-fix#10]
Hi, thanks for the awesome fix.

I just want to say something, if anyone runs into it too.
Make sure you enter the actual skype binary path next to the LD_PRELOAD and not just skype.
In my system, the command skype resolves to file /bin/skype that is a bash script, so when I tried to run LD_PRELOAD=/full_path/skype-poll-fix.so skype, the LD_PRELOAD would fail.

**Comment by ValdikSS** [comment]
Or you can just edit said bash script. Skype doesn't update often.
