### ISSUE TITLE
Links not opening

### ISSUE THREAD

**Issue by ettavolt** [ValdikSS/skype-poll-fix#12]
For ``3.19.0-31-generic #36~14.04.1-Ubuntu i686 GNU/Linux`` I had to move ``-ldl`` flag to the end of compiler command. Otherwise there were ``undefined symbol: dlsym`` errors after clicking on links in chat. ``ldd skype-poll-fix.so`` showed that ``libdl.so.2`` was not linked to.
With this fix it takes 3~4s for Skype to open a link. :) Most likely we can't do much to decrease this time except not applying the fix.

**Comment by ValdikSS** [comment]
Thanks!
