### ISSUE TITLE
How generalizable is this?

### ISSUE THREAD

**Issue by axfelix** [ValdikSS/skype-poll-fix#14]
My C experience is super limited, but I notice Vidyo (another teleconferencing app I need to use for work) has similar idle CPU usage to Skype (before using this fix) on Linux, and I wonder if it might've been written the same way.

Are all of the calls in your script written against Skype itself? I'd assume not because Skype's source is obfuscated...

Anyway, thanks for this, works great.

**Comment by ValdikSS** [comment]
Well, it could impair performance and stability of the software. But you can try it anyway.

**Comment by axfelix** [comment]
Preliminarily, it appears to work!

**Comment by axfelix** [comment]
The effect isn't as dramatic (CPU wasn't quite as bad as it was for Skype, and it didn't drop to nearly nothing after using this fix), but it definitely helped, and seemingly no new issues were caused.
