### ISSUE TITLE
Doesn't seem to want to preload a 32-bit library on Arch

### ISSUE THREAD

**Issue by axfelix** [ValdikSS/skype-poll-fix#16]
[axfelix@nixon skype-poll-fix]$ env LD_PRELOAD=/opt/skype-poll-fix.so skype %U
ERROR: ld.so: object '/opt/skype-poll-fix.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

I'm assuming this is somehow specific to my environment, but I'm not sure what'd be causing it, as it works fine on my 64-bit Ubuntu machine.

**Comment by ValdikSS** [comment]
Could it be that you're trying preload library to the shell script?
Please read README.md.

**Comment by axfelix** [comment]
Aha. Yup. I only checked whether which skype was a symlink, not whether the file itself was a shell script, which it was. Fixed by adding the second-to-last-line.

[axfelix@nixon ~]$ cat /usr/bin/skype
#!/bin/bash

LIBDIR="/usr/lib32"

if [[ -e "$LIBDIR/libv4l/v4l2convert.so" ]]; then
	export LD_PRELOAD="${LD_PRELOAD:+$LD_PRELOAD:}$LIBDIR/libv4l/v4l2convert.so"
fi

if [[ -e "/usr/share/skype/lib/libQtWebKit.so.4" ]]; then
	export LD_PRELOAD="${LD_PRELOAD:+$LD_PRELOAD:}/usr/share/skype/lib/libQtWebKit.so.4"
fi

export LD_PRELOAD=/opt/skype-poll-fix.so:$LD_PRELOAD
exec "$LIBDIR/skype/skype" "$@"

Feel free to add this to the readme for Arch users.
